#!/bin/bash

# Abort on Error
set -euo pipefail

# Determine toolpath if not set already
relativepath="../" # Define relative path to go from this script to the root level of the tool
if [[ ! -v toolpath ]]; then scriptpath=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ); toolpath=$(realpath --canonicalize-missing ${scriptpath}/${relativepath}); fi

# Load Configuration
source "${toolpath}/config.sh"

# Load Functions
source "${toolpath}/functions.sh"

# Set error trap AFTER sourcing
trap 'error_handler $? $LINENO "$BASH_SOURCE"' ERR

# ============================================
# Install Container Configuration Files
# ============================================
# Installs 6 config files to their standard system paths:
#   1. containers.conf  -> /etc/containers/containers.conf
#   2. seccomp.json     -> /usr/share/containers/seccomp.json
#   3. policy.json      -> /etc/containers/policy.json
#   4. default.yaml     -> /etc/containers/registries.d/default.yaml
#   5. storage.conf     -> /etc/containers/storage.conf
#   6. registries.conf  -> /etc/containers/registries.conf

step_start "Creating configuration directories"
mkdir -p /etc/containers
mkdir -p /etc/containers/registries.d
mkdir -p /usr/share/containers
step_done

step_start "Installing configuration files"

# 1. containers.conf (from project config/ directory)
echo "  Installing containers.conf -> /etc/containers/containers.conf"
install -m 0644 "${toolpath}/config/containers.conf" /etc/containers/containers.conf

# 2. seccomp.json (generated by Phase 11 container-libs build)
SECCOMP_SRC="${BUILD_ROOT}/container-libs/seccomp.json"
if [ ! -f "${SECCOMP_SRC}" ]; then
    # Fallback: the Makefile target is in common/ subdir
    SECCOMP_SRC="${BUILD_ROOT}/container-libs/common/seccomp.json"
fi
if [ ! -f "${SECCOMP_SRC}" ]; then
    echo "ERROR: seccomp.json not found at ${BUILD_ROOT}/container-libs/seccomp.json or ${BUILD_ROOT}/container-libs/common/seccomp.json" >&2
    exit 1
fi
echo "  Installing seccomp.json -> /usr/share/containers/seccomp.json"
install -m 0644 "${SECCOMP_SRC}" /usr/share/containers/seccomp.json

# 3. policy.json
echo "  Installing policy.json -> /etc/containers/policy.json"
install -m 0644 "${BUILD_ROOT}/container-libs/image/default-policy.json" /etc/containers/policy.json

# 4. default.yaml
echo "  Installing default.yaml -> /etc/containers/registries.d/default.yaml"
install -m 0644 "${BUILD_ROOT}/container-libs/image/default.yaml" /etc/containers/registries.d/default.yaml

# 5. storage.conf
echo "  Installing storage.conf -> /etc/containers/storage.conf"
install -m 0644 "${BUILD_ROOT}/container-libs/storage/storage.conf" /etc/containers/storage.conf

# 6. registries.conf
echo "  Installing registries.conf -> /etc/containers/registries.conf"
install -m 0644 "${BUILD_ROOT}/container-libs/image/registries.conf" /etc/containers/registries.conf

step_done

step_start "Verifying installed configuration files"
VERIFY_OK=true

for dest in \
    /etc/containers/containers.conf \
    /usr/share/containers/seccomp.json \
    /etc/containers/policy.json \
    /etc/containers/registries.d/default.yaml \
    /etc/containers/storage.conf \
    /etc/containers/registries.conf; do
    if test -f "${dest}"; then
        echo "  OK: ${dest}"
    else
        echo "  MISSING: ${dest}" >&2
        VERIFY_OK=false
    fi
done

if [ "${VERIFY_OK}" = false ]; then
    echo "ERROR: One or more configuration files failed to install" >&2
    exit 1
fi

echo "  All 6 configuration files installed successfully"
step_done
